SRM_MVC/Controllers/BranchController.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using SRM_MVC.Services;
using SRM_MVC.Models;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace SRM_MVC.Controllers
{
    public class BranchController : Controller
    {
        private IBranchService _service = null;
        CoursesService _cservice = new CoursesService();
        public BranchController(IBranchService service)
        {
            _service = service;
        }

        [HttpGet]
        public IActionResult AddBranch()
        {
           
            List<SelectListItem> courseslist = _cservice.GetCourses().Select(n => new SelectListItem { Value = n.CourseId.ToString(), Text = n.CourseName }).ToList(); ;

            var courseTip = new SelectListItem()
            {
                Value = null,
                Text = "--- select Course ---"
            };
            courseslist.Insert(0, courseTip);
            ViewBag.courseslist = new SelectList(courseslist, "Value", "Text");
            return View();
        }
        [HttpPost]
        public IActionResult AddBranch(Branch branch)
        {

            List<SelectListItem> courseslist = _cservice.GetCourses().Select(n => new SelectListItem { Value = n.CourseId.ToString(), Text = n.CourseName }).ToList(); ;

            var courseTip = new SelectListItem()
            {
                Value = null,
                Text = "--- select Course ---"
            };
            _service.AddBranch(branch);
            return RedirectToAction("GetBranchs");

        }

        [HttpGet]
        public IActionResult GetBranchs()
        {

            return View(_service.GetBranchs());
        }

        [HttpGet]

        public IActionResult Get(int id)
        {
            try
            {
                var courses = _service.GetBranch(id);
                if (courses != null)
                    return Ok(courses);
                else
                    return Content("Invalid Id");
            }
            catch (Exception ex)
            {

                return Content(ex.Message);
            }
        }

        [HttpGet]
        public IActionResult Edit(int id)
        {
            Branch course = _service.GetBranch(id);
            return View(course);
        }
        [HttpPost]

        public IActionResult Edit(Branch branch)
        {
            _service.UpdateBranch(branch);

            return RedirectToAction("GetBranchs");
        }
        [HttpGet]

        public IActionResult Delete(int id)
        {
            Branch branch = _service.GetBranch(id);

            return View(branch);
        }

        [HttpPost]
        public IActionResult Delete(Branch branch)
        {
            _service.DeleteBranch(branch.BId);

            return RedirectToAction("GetBranchs");
        }
    }
}

SRM_MVC/Controllers/CourseController.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using SRM_MVC.Models;
using SRM_MVC.Services;
using Microsoft.AspNetCore.Http;

namespace SRM_MVC.Controllers
{
    public class CourseController : Controller
    {
        private ICoursesService _service = null;
        public CourseController(ICoursesService service)
        {
            _service = service;
        }

        [HttpGet]
        public IActionResult AddCourse()
        {
            return View();
        }
        [HttpPost]
        public  IActionResult AddCourse(Courses course)
        {
            _service.AddCourse(course);
            return View();

        }

        [HttpGet]
        public IActionResult GetCourses()
        {
            
            return View(_service.GetCourses());
        }

        [HttpGet]
       
        public IActionResult Get(int id)
        {
            try
            {
                var courses = _service.GetCourse(id);
                if (courses != null)
                    return Ok(courses);
                else
                    return Content("Invalid Id");
            }
            catch (Exception ex)
            {

                return Content(ex.Message);
            }
        }



        
        [HttpGet]
        public IActionResult Edit(int id)
        {
            Courses course= _service.GetCourse(id);
            return View(course);
        }
        [HttpPost]

        public IActionResult Edit(Courses course)
        {
            _service.UpdateCourse(course);

            return RedirectToAction("GetCourses");
        }
        [HttpGet]
        
        public IActionResult Delete(int id)
        {
            Courses course= _service.GetCourse(id);

             return View(course);
        }

        [HttpPost]        
        public IActionResult Delete(Courses course)
        {
            _service.DeleteCourse(course.CourseId);

            return RedirectToAction("GetCourses");
        }

    }
}

SRM_MVC/Controllers/ResultController.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using SRM_MVC.Services;
using SRM_MVC.Models;
using Microsoft.AspNetCore.Mvc.Rendering;

namespace SRM_MVC.Controllers
{
    public class ResultController : Controller
    {
        private readonly IResultService _service = null;
        private readonly ISemesterService _semservice = null;
        private readonly IBranchService _branchService = null;
        private readonly IStudentService _studentService = null;
        private readonly ISubjectService _subjectService = null;
         //SemesterService semservices = new SemesterService();
        
        public ResultController(IResultService service,ISemesterService ssemester, IBranchService bservice, IStudentService sservice,ISubjectService subservice)
        {
            _service = service;
            _semservice = ssemester;
            _branchService = bservice;
            _studentService = sservice;
            _subjectService = subservice;
        }
        [HttpGet]
        public IActionResult AddResult()
        {
            //Name and Id can alter
            List<SelectListItem> studentList = _studentService.GetStudents().Select(n => new SelectListItem { Value = n.StudentId.ToString(), Text = n.FirstName }).ToList(); ;
            var stdTip = new SelectListItem()
            {
                Value = null,
                Text = "--- select Student ---"
            };
           
            List<SelectListItem> semlist = _semservice.GetSemesters().Select(n => new SelectListItem { Value = n.SemesterId.ToString(), Text = n.semester }).ToList(); ;
            var semTip = new SelectListItem()
            {
                Value = null,
                Text = "--- select Semester ---"
            };
            List<SelectListItem> SubjectList = _subjectService.GetSubjects().Select(n => new SelectListItem { Value = n.SubjectId.ToString(), Text = n.SubjectName }).ToList(); ;
            var subTip = new SelectListItem()
            {
                Value = null,
                Text = "--- select Subject ---"
            };

            studentList.Insert(0, stdTip);
            semlist.Insert(0, semTip);
            SubjectList.Insert(0, subTip);
            ViewBag.studentList = new SelectList(studentList, "Value", "text");
            ViewBag.SubjectList = new SelectList(SubjectList, "Value", "text");
            ViewBag.semslist = new SelectList(semlist, "Value","text");

            return View();

        }

        [HttpPost]
        public IActionResult AddResult(Result result)
        {
            List<SelectListItem> studentList = _studentService.GetStudents().Select(n => new SelectListItem { Value = n.StudentId.ToString(), Text = n.FirstName }).ToList(); ;
            var stdTip = new SelectListItem()
            {
                Value = null,
                Text = "--- select Student ---"
            };
            List<SelectListItem> SubjectList = _studentService.GetStudents().Select(n => new SelectListItem { Value = n.StudentId.ToString(), Text = n.FirstName }).ToList(); ;
            var subTip = new SelectListItem()
            {
                Value = null,
                Text = "--- select Subject ---"
            };
            List<SelectListItem> semlist = _semservice.GetSemesters().Select(n => new SelectListItem { Value = n.SemesterId.ToString(), Text = n.semester }).ToList(); ;
            var semTip = new SelectListItem()
            {
                Value = null,
                Text = "--- select Semester ---"
            };


            studentList.Insert(0, stdTip);
            SubjectList.Insert(0, subTip);
            semlist.Insert(0, semTip);
            ViewBag.studentList = new SelectList(studentList, "Value", "text");
            ViewBag.SubjectList = new SelectList(SubjectList, "Value", "text");
            ViewBag.semslist = new SelectList(semlist, "Value", "text");

            return RedirectToAction("GetResults");
            //return View();

        }
        [HttpGet]
        public IActionResult GetResults()
        {

            return View(_service.GetResults());
        }

        [HttpGet]

        public IActionResult Get(int id)
        {
            try
            {
                var result = _service.GetResult(id);
                if (result != null)
                    return Ok(result);
                else
                    return Content("Invalid Id");
            }
            catch (Exception ex)
            {

                return Content(ex.Message);
            }
        }

        [HttpGet]
        public IActionResult Edit(int id)
        {
            Result result = _service.GetResult(id);
            return View(result);
        }
        [HttpPost]

        public IActionResult Edit(Result reslut)
        {
            _service.UpdateResult(reslut);

            return RedirectToAction("GetResults");
        }
        [HttpGet]

        public IActionResult Delete(int id)
        {
            Result reult = _service.GetResult(id);

            return View(reult);
        }

        [HttpPost]
        public IActionResult Delete(Result result)
        {
            _service.DeleteResult(result.ResultId);

            return RedirectToAction("GetResults");
        }
    }
}

SRM_MVC/Controllers/UserController.cs
using Microsoft.AspNetCore.Mvc;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using SRM_MVC.Services;
using Microsoft.AspNetCore.Mvc.Rendering;
 using SRM_MVC.Models;

namespace SRM_MVC.Controllers
{
    public class UserController : Controller
    {
        private readonly IStudentService _studentService = null;
        private readonly ISemesterService _semservice = null;
        private readonly IBranchService _branchService = null;

        public UserController(ISemesterService sservice, IBranchService bservice, IStudentService stservice)
        {
            _semservice = sservice;
            _branchService = bservice;
            _studentService = stservice;
        }
        [HttpGet]
        public IActionResult GetStudentResult()
        {

            
            List<SelectListItem> semLiIst = _semservice.GetSemesters().Select(n => new SelectListItem { Value = n.SemesterId.ToString(), Text = n.semester }).ToList(); ;

            var SemTip = new SelectListItem()
            {
                Value = null,
                Text = "--- select Semester ---"
            };
           
            //StudentList.Insert(0, StuTip);
            semLiIst.Insert(0, SemTip);
            //ViewBag.StudentList = new SelectList(StudentList, "Value", "Text");
            ViewBag.semLiIst = new SelectList(semLiIst, "Value", "Text");
            return View();
        }
       

        [HttpPost]
        public IActionResult DetailsResult(int id, int brid, int semid)
        {

            return View();            
        }

        public IActionResult Index()
        {
            return View();
        }


        
    }
}

SRM_MVC/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - SRM_MVC</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">SRMS</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex justify-content-between">
                    <ul class="navbar-nav flex-grow-1">
                        @*<li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Admin" asp-action="GetAdmins">Lists Admin</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Branch" asp-action="GetBranchs">List Branch</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Course" asp-action="GetCourses">List Courses</a>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Subject" asp-action="GetSubjects">List Subject </a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Semester" asp-action="GetSemester">get sem</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Student" asp-action="GetStudents">List Student</a>
                        </li>*@
                        @*<li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Result" asp-action="GetResults">Get Result</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="User" asp-action="GetStudentResult">Get Student Result</a>
                        </li>*@



                    </ul>
                </div>
            </div>
        </nav>
    </header>
    @*------------changes-------------*@
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>
    @*--------------------------------*@
    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2021 - SRM_MVC - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @await RenderSectionAsync("Scripts", required: false)
</body>
</html>